### ISSUE TITLE
Loader Logic

### ISSUE THREAD

**Issue by Max93** [lovethesign/jeffrey#32]
Right now there isn't a logic for loading component. I don't know if better solution is using a classic loader, no one or a placeholder like [reference](https://zalog.ro/placeholder-loading/).

This is a solution from old project:

```css
.Loader
  position: absolute
  top: 0
  left: 0
  min-width: rem-calc(64)
  width: 100%
  min-height: rem-calc(64)
  height: 100%
  line-height: 0
  background-color: rgba(255,255,255,.75)
  z-index: 99
  &:hover
    cursor: wait
  > svg
    background-color: $color-blank
    padding: rem-calc(8)
    clip-path: circle(50% at 50% 50%)
  &--Alternative
    background-color: rgba(0,0,0,.75)
    > svg
      background-color: #222
      fill: $color-blank
  &--Transparent
    background-color: rgba(0,0,0,0)
  &--Fixed
    position: fixed
```
@raziel8 please submit here your solution.

I'm sure what we don't want:

![reference](https://user-images.githubusercontent.com/3720947/48716561-f0040b80-ec17-11e8-8dde-9f781931eddd.gif)

**Comment by raziel8** [comment]
What a shame, actually the loader is beautiful
