### ISSUE TITLE
missing iconset for following icons

### ISSUE THREAD

**Issue by raziel8** [lovethesign/jeffrey#39]
- [ ] heart (outline & filled)

- [ ] fast shipping

- [ ] loading

keep in mind to made all the icons in black.

**Comment by Max93** [comment]
Please create an SVGs like follow:
 
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/500px.svg

**Comment by raziel8** [comment]
[icons.zip](https://github.com/lovethesign/jeffrey/files/2629435/icons.zip)

**Comment by raziel8** [comment]
how do you think is the best option to import them into the project? (feature branch? etc..)
