### ISSUE TITLE
Init Layout Logic

### ISSUE THREAD

**Issue by Max93** [lovethesign/jeffrey#9]
Implement grid logic.

[reference 1](https://philipwalton.github.io/solved-by-flexbox/)
[reference 2](https://github.com/h0r0m4n/vademecum)

**Comment by raziel8** [comment]
"Grid" is usually used to define a two dimensional structure, which help graphic and web designers to set up the entire layout and organize all the components.

We are not ready to define an entire (too forcing) grid system. Instead is better to define general layout rules with the help of Flexbox.

**Comment by Max93** [comment]
Layouting with Flexbox sound perfect!
I'm waiting for a PL. I think the best way is create a feature branch like *feature/layout*.
Please 🙏  remember the prefix lts-* for classes.
To match idea before start I ask you to past here links and thinks.
Thanks a lot mr @raziel8.
